spring.datasource.url=jdbc:postgresql://localhost:5432/produtosdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.security.oauth2.client.registration.github.client-id=SEU_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=SEU_CLIENT_SECRET